name: docker build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -  
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      run: |
        docker buildx build \
        --platform linux/arm64 \
        -t ${{ REPO_USER }}/graviton:latest \
        --push \
        .
